{{- if or (not .Values.global.externalSecrets.deploy) (and .Values.global.externalSecrets.deploy .Values.externalSecrets.createCedarClientSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: cedar-g3auto
type: Opaque
stringData:
  cedar_api_key.txt: |
    {{ .Values.secrets.apiKey }}
{{- end }}