{{- if .Values.global.crossplane.enabled }}
apiVersion: iam.aws.crossplane.io/v1beta1
kind: Role
metadata:
  name: "{{ .Values.global.environment }}-{{ .Release.Namespace }}-{{ include "gearbox-middleware.serviceAccountName" . }}"
spec:
  providerConfigRef:
    name: provider-aws
  forProvider:
    name: "{{ .Values.global.environment }}-{{ .Release.Namespace }}-{{ include "gearbox-middleware.serviceAccountName" . }}"
    description: "Role for gearbox-middleware service account for {{ .Values.global.environment }}"
    assumeRolePolicyDocument: |
      {
        "Version":"2012-10-17",
        "Statement":[
          { "Effect":"Allow","Principal":{"Service":"ec2.amazonaws.com"},"Action":"sts:AssumeRole" },
          {
            "Sid":"",
            "Effect":"Allow",
            "Principal":{"Federated":"arn:aws:iam::{{ .Values.global.crossplane.accountId }}:oidc-provider/{{ .Values.global.crossplane.oidcProviderUrl }}"},
            "Action":"sts:AssumeRoleWithWebIdentity",
            "Condition":{
              "StringEquals":{
                "{{ .Values.global.crossplane.oidcProviderUrl }}:sub":"system:serviceaccount:{{ .Release.Namespace }}:{{ include "gearbox-middleware.serviceAccountName" . }}",
                "{{ .Values.global.crossplane.oidcProviderUrl }}:aud":"sts.amazonaws.com"
              }
            }
          }
        ]
      }
---
apiVersion: iam.aws.crossplane.io/v1beta1
kind: Policy
metadata:
  name: "{{ .Values.global.environment }}-{{ .Release.Namespace }}-gearbox-middleware-role-policy"
spec:
  providerConfigRef:
    name: provider-aws
  forProvider:
    roleName: "{{ .Values.global.environment }}-{{ .Release.Namespace }}-{{ include "gearbox-middleware.serviceAccountName" . }}"
    name: "{{ .Values.global.environment }}-{{ .Release.Namespace }}-gearbox-middleware-role-policy"
    document: |
      {
        "Version":"2012-10-17",
        "Statement":[
          {
            "Effect":"Allow",
            "Action":["s3:List*","s3:Get*"],
            "Resource":[
              "arn:aws:s3:::{{ .Values.global.environment }}-{{ .Release.Namespace }}-gearbox-middleware-bucket/*",
              "arn:aws:s3:::{{ .Values.global.environment }}-{{ .Release.Namespace }}-gearbox-middleware-bucket"
            ]
          },
          {
            "Effect":"Allow",
            "Action":["s3:PutObject","s3:GetObject","s3:DeleteObject"],
            "Resource":"arn:aws:s3:::{{ .Values.global.environment }}-{{ .Release.Namespace }}-gearbox-middleware-bucket/*"
          }
        ]
      }

---
apiVersion: iam.aws.crossplane.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: "{{ include "gearbox-middleware.serviceAccountName" . }}-{{ .Release.Namespace }}-managed-policy-attachment"
spec:
  providerConfigRef:
    name: provider-aws
  forProvider:
    roleName: "{{ .Values.global.environment }}-{{ .Release.Namespace }}-{{ include "gearbox-middleware.serviceAccountName" . }}"
    policyArnRef: 
      name: "{{ .Values.global.environment }}-{{ .Release.Namespace }}-gearbox-middleware-role-policy"
---
apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
  name: "{{ .Values.global.environment }}-{{ .Release.Namespace }}-gearbox-middleware-bucket"
spec:
  providerConfigRef:
    name: provider-aws
  forProvider:
    bucketName: "{{ .Values.global.environment }}-{{ .Release.Namespace }}-gearbox-middleware-bucket"
    acl: private
    forceDestroy: false
    locationConstraint: {{ .Values.global.aws.region }}
    tags:
      Organization: gen3
      description: Created by crossplane
    versioningConfiguration:
      {{- if .Values.global.crossplane.s3.versioningEnabled }}
      status: "Enabled"
      {{- end }}
    serverSideEncryptionConfiguration:
      rules:
        - applyServerSideEncryptionByDefault:
            sseAlgorithm: aws:kms
            {{- if .Values.global.crossplane.s3.kmsKeyId }}
            kmsMasterKeyID: {{ .Values.global.crossplane.s3.kmsKeyId }}
            {{- end }}
{{- end}}            