{{- if and .Values.global.pdb (.Values.global.dev) }}
{{ if .Values.postgresql.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: postgres-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
       app.kubernetes.io/name: "postgresql"
{{- end }}
---
{{ if .Values.elasticsearch.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: elasticsearch-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: "gen3-elasticsearch-master"
{{- end }}
{{- end }}
