apiVersion: v1
kind: ConfigMap
metadata:
  name: ohdsi-webapi-reverse-proxy-config
data:
  nginx.conf: |
    user nginx;
    worker_processes  1;
    events {
      worker_connections  10240;
    }
    http {
      server {
          listen       80;
          server_name  localhost;
          resolver kube-dns.kube-system.svc.cluster.local ipv6=off;
          location / {
            set $proxy_service "ohdsi-webapi";
            # upstream is written to logs
            set $upstream http://localhost:8080;
            proxy_pass $upstream;
            proxy_set_header Host atlas.{{ .Values.global.hostname }};
            proxy_redirect http://atlas.{{ .Values.global.hostname }}/ https://atlas.{{ .Values.global.hostname }}/;
            client_max_body_size 0;
            add_header Content-Security-Policy "frame-ancestors 'self' https://{{ .Values.global.hostname }}" always;
        }
      }
    }