apiVersion: v1
kind: ServiceAccount
metadata:
  name: webapi-secrets
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: webapi-secrets-role
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets"]
  resourceNames: ["ohdsi-webapi-config"]
  verbs: ["get", "patch"]
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["fence-dbcreds"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: webapi-secrets-rolebinding
subjects:
- kind: ServiceAccount
  name: webapi-secrets
  apiGroup: ""
roleRef:
  kind: Role
  name: webapi-secrets-role
  apiGroup: ""
