{{ if .Values.global.externalSecrets.deploy }}
{{- if not .Values.externalSecrets.createK8sGen3WorkflowSecret}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gen3workflow-g3auto
spec:
  refreshInterval: 5m
  secretStoreRef:
    {{- if ne .Values.global.externalSecrets.clusterSecretStoreRef "" }}
    name: {{ .Values.global.externalSecrets.clusterSecretStoreRef }}
    kind: ClusterSecretStore
    {{- else }}
    name: {{include "common.SecretStore" .}}
    kind: SecretStore
    {{- end }}
  target:
    name: gen3workflow-g3auto
    creationPolicy: Owner
  data:
  - secretKey: gen3-workflow-config.yaml
    remoteRef:
      #name of secret in secrets manager
      key: {{include "gen3workflow-g3auto" .}}
      property: gen3-workflow-config.yaml
{{- end }}
{{- end }}
