{{- $jobsNamespace := default (printf "gen3-%s-workflow-pods" .Release.Namespace) .Values.funnel.Kubernetes.JobsNamespace }}

{{- if ne $jobsNamespace .Release.Namespace }}
apiVersion: v1
kind: Namespace
metadata:
    name: {{ $jobsNamespace | quote }}
    labels:
        app.kubernetes.io/name: {{ $jobsNamespace | quote }}
{{- end }}
