{{- if and (.Values.global.externalSecrets.deploy) (not .Values.externalSecrets.createK8sgearboxSecret) }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gearbox-g3auto
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: {{include "common.SecretStore" .}}
    kind: SecretStore
  target:
    name: gearbox-g3auto
    creationPolicy: Owner
  data:
  - secretKey: config.json
    remoteRef:
      #name of secret in secrets manager
      key: {{include "gearbox-g3auto" .}}
{{- end }}