{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gearbox.serviceAccountName" . }}
  labels:
    {{- include "gearbox.labels" . | nindent 4 }}
  {{- if .Values.global.crossplane.enabled }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.global.crossplane.accountId }}:role/{{ .Values.global.environment }}-{{ .Release.Namespace }}-{{ include "gearbox.serviceAccountName" . }}
  {{- else }}
  {{ with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end }}
