{{- if and (.Values.global.externalSecrets.deploy) (not .Values.externalSecrets.createK8sStataSecret) }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: stata-worspace-gen3-license
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: {{include "common.SecretStore" .}}
    kind: SecretStore
  target:
    name: stata-worspace-gen3-license
    creationPolicy: Owner
  data:
  - secretKey: stata-license.txt
    remoteRef:
      #name of secret in secrets manager
      key: {{include "stata-worspace-gen3-license" .}}
{{- end }}
---
{{- if and (.Values.global.externalSecrets.deploy) (not .Values.global.externalSecrets.dbCreate) }}
{{ include "common.externalSecret.db" . }}
{{- end }}