apiVersion: v1
kind: Secret
metadata:
  name: amanuensis-secret
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
type: Opaque
data:
{{ (.Files.Glob "amanuensis-secret/*").AsSecrets | indent 2 }}
---

