{{- if .Values.amanuensisJobs.dbMigrateJob }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: amanuensis-db-migrate
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    app: gen3-created-by-hook
spec:
  template:
    metadata:
      labels:
        app: gen3job
    spec:
      automountServiceAccountToken: false
      volumes:
        - name: yaml-merge
          configMap:
            name: "amanuensis-yaml-merge"
            optional: true
        - name: config-volume
          secret:
            secretName: "amanuensis-config"
            items:
              - key: amanuensis-config.yaml
                path: amanuensis-config.yaml
            optional: false
        - name: amanuensis-volume
          secret:
            secretName: "amanuensis-creds"
            items:
              - key: creds.json
                path: creds.json
            optional: false
        - name: tmp-pod
          emptyDir: {}
      containers:
      - name: amanuensis
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: PYTHONPATH
            value: /var/www/amanuensis
          - name: AMANUENSIS_PUBLIC_CONFIG
            valueFrom:
              configMapKeyRef:
                name: manifest-amanuensis
                key: amanuensis-config-public.yaml
                optional: true
        volumeMounts:
          - name: "config-volume"
            readOnly: true
            mountPath: "/var/www/amanuensis/amanuensis-config.yaml"
            subPath: amanuensis-config.yaml
          - name: "yaml-merge"
            readOnly: true
            mountPath: "/var/www/amanuensis/yaml_merge.py"
            subPath: yaml_merge.py
          - name: "amanuensis-volume"
            readOnly: true
            mountPath: "/var/www/amanuensis/creds.json"
            subPath: creds.json
        command: ["/bin/bash"]
        args:
          - "-c"
          - |
            # echo "${AMANUENSIS_PUBLIC_CONFIG:-""}" > "/var/www/amanuensis/amanuensis-config-public.yaml"
            # python /var/www/amanuensis/yaml_merge.py /var/www/amanuensis/amanuensis-config-public.yaml /var/www/amanuensis/amanuensis-config-secret.yaml > /var/www/amanuensis/amanuensis-config.yaml
            cd /amanuensis
            fence-create migrate
            if [[ $? != 0 ]]; then
              echo "WARNING: non zero exit code: $?"
              exit 1
            fi
      restartPolicy: OnFailure

{{- end }}