{{ if .Values.global.externalSecrets.deploy }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: amanuensis-config
spec:
  refreshInterval: 5m
  secretStoreRef:
   {{- if ne .Values.global.externalSecrets.clusterSecretStoreRef  "" }}
    name: {{ .Values.global.externalSecrets.clusterSecretStoreRef }}
    kind: ClusterSecretStore
  {{- else }}
    name: {{include "common.SecretStore" .}}
    kind: SecretStore
  {{- end  }}
  target:
    name: amanuensis-config
    creationPolicy: Owner
  data:
  - secretKey: amanuensis-config.yaml
    remoteRef:
      #name of secret in secrets manager
      key: {{include "amanuensis-config" .}}
---
{{- if and (.Values.global.externalSecrets.deploy) (not .Values.global.externalSecrets.dbCreate) }}
{{ include "common.externalSecret.db" . }}
{{- end}}
{{- end}}