{{ if .Values.externalSecrets.deploy }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: google-creds-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: {{include "common.SecretStore" .}}
    kind: SecretStore
  target:
    name: google-creds-secret
    creationPolicy: Owner
  data:
  - secretKey: google-creds-secret
    remoteRef:
      #name of secret in secrets manager
      key: {{include "external-secrets.googleCredsSecretName" .}}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aws-creds-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: {{include "common.SecretStore" .}}
    kind: SecretStore
  target:
    name: aws-creds-secret
    creationPolicy: Owner
  data:
  - secretKey: credentials
    remoteRef:
      #name of secret in secrets manager
      key: {{include "external-secrets.awsCredsSecretName" .}}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dcf-dataservice-settings-secrets
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: {{include "common.SecretStore" .}}
    kind: SecretStore
  target:
    name: dcf-dataservice-settings-secrets
    creationPolicy: Owner
  data:
  - secretKey: dcf-dataservice-settings-secrets
    remoteRef:
      #name of secret in secrets manager
      key: {{include "external-secrets.dcfDataserviceSettingsSecretName" .}}
{{- end }}
