apiVersion: v1
kind: ServiceAccount
metadata:
  name: google-bucket-replicate-job
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: google-bucket-replicate-job-role
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: google-bucket-replicate-job-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: google-bucket-replicate-job-role
subjects:
  - kind: ServiceAccount
    name: google-bucket-replicate-job