{{ if .Values.global.externalSecrets.deploy }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gen3discoveryai-g3auto
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: {{include "common.SecretStore" .}}
    kind: SecretStore
  target:
    name: gen3discoveryai-g3auto
    creationPolicy: Owner
  data:
  - secretKey: base64Authz.txt
    remoteRef:
      #name of secret in secrets manager
      key: {{include "gen3discoveryai-g3auto" .}}
      property: base64Authz.txt
  - secretKey: gen3-discovery-ai.env
    remoteRef:
      #name of secret in secrets manager
      key: {{include "gen3discoveryai-g3auto" .}}
      property: gen3-discovery-ai.env
{{- end }}
---
{{- if and .Values.global.externalSecrets.deploy (not .Values.global.externalSecrets.createLocalK8sSecret) }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gen3discoveryai-google-adc
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: {{include "common.SecretStore" .}}
    kind: SecretStore
  target:
    name: gen3discoveryai-google-adc
    creationPolicy: Owner
  data:
  - secretKey: gen3discoveryai-google-adc
    remoteRef:
      #name of secret in secrets manager
      key: {{include "gen3discoveryai-g3auto" .}}
      property: application_default_credentials.json
{{- end }}
{{- if and .Values.global.externalSecrets.deploy (not .Values.global.externalSecrets.createLocalK8sSecret) }}
{{ include "common.externalSecret.db" . }}
{{- end }}