apiVersion: v2
name: cluster-level-resources
description: An app-of-apps Helm chart that allows for flexible deployment of resources that support Gen3

type: application

version: 0.6.7

appVersion: "1.17.0"
