{{ include "common.db-secret" . }}
---
{{ include "common.db_setup_sa" . }}
---
{{ include "common.db_setup_job" . }}
{{- if and $.Values.global.externalSecrets.deploy (or $.Values.global.externalSecrets.pushSecret .Values.externalSecrets.pushSecret) }}
---
{{ include "common.db-push-secret" . }}
---
{{ include "common.secret.db.bootstrap" . }}
{{- end }}