{{- if not .Values.externalSecrets.createK8sOrthancS3G3auto}}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: orthanc-s3-g3auto
spec:
  refreshInterval: 5m
  secretStoreRef:
   {{- if ne .Values.global.externalSecrets.clusterSecretStoreRef  "" }}
    name: {{ .Values.global.externalSecrets.clusterSecretStoreRef }}
    kind: ClusterSecretStore
  {{- else }}
    name: {{include "common.SecretStore" .}}
    kind: SecretStore
  {{- end  }}
  target:
    name: orthanc-s3-g3auto
    creationPolicy: Owner
  data:
  - secretKey: orthanc_config_overwrites.json
    remoteRef:
      #name of secret in secrets manager
      key: {{include "orthanc-s3-g3auto" .}}
{{- end }}
{{- if or .Values.global.externalSecrets.deploy (and .Values.global.externalSecrets.dbCreate .Values.postgres.bootstrap) }}

---
{{ include "common.externalSecret.db" . }}
{{- end }}