{{ if .Values.global.externalSecrets.deploy }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ems-g3auto
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: {{include "common.SecretStore" .}}
    kind: SecretStore
  target:
    name: ems-g3auto
    creationPolicy: Owner
  data:
  - secretKey: base64Authz.txt
    remoteRef:
      #name of secret in secrets manager
      key: {{include "ems-g3auto" .}}
      property: base64Authz.txt
  - secretKey: dbcreds.json
    remoteRef:
      #name of secret in secrets manager
      key: {{include "ems-g3auto" .}}
      property: dbcreds.json
  - secretKey: ems.env
    remoteRef:
      #name of secret in secrets manager
      key: {{include "ems-g3auto" .}}
      property: ems.env
{{- end }}
---
{{ include "common.externalSecret.db" . }}