{{ if index .Values "metrics-server" "enabled" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
spec:
  project: default
  sources:
    - chart: metrics-server
      repoURL: https://kubernetes-sigs.github.io/metrics-server/
      targetRevision: {{ index .Values "metrics-server" "targetRevision" }}
      helm:
        releaseName: metrics-server
      {{- if index .Values "metrics-server" "configuration" "enabled" }}
        valueFiles:
          - $values/{{ .Values.cluster }}/cluster-values/metrics-server.yaml
    - repoURL: {{ .Values.configuration.configurationRepo }}
      targetRevision: {{ .Values.configuration.configurationRevision }}
      ref: values
      {{- else }}
        values: |
          hostNetwork:
            enabled: {{ index .Values "metrics-server" "hostNetworkEnabled" }}
          args:
            - --secure-port=4443
            - --kubelet-insecure-tls
            - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
            - --kubelet-use-node-status-port
            - --metric-resolution=15s
      {{- end }}
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
  syncPolicy:
    syncOptions:
    - CreateNamespace=false
    automated:
      selfHeal: true
{{ end }}
