{{ if index .Values "nvidia-device-plugin" "enabled" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nvidia-device-plugin
  namespace: argocd
spec:
  project: default
  sources:
    - chart: nvidia-device-plugin
      repoURL: https://nvidia.github.io/k8s-device-plugin
      targetRevision: {{ index .Values "nvidia-device-plugin" "targetRevision" }}
      helm:
        releaseName: nvidia-device-plugin
      {{- if index .Values "nvidia-device-plugin" "configuration" "enabled" }}
        valueFiles:
          - $values/{{ .Values.cluster }}/cluster-values/nvidia-device-plugin.yaml
    - repoURL: {{ .Values.configuration.configurationRepo }}
      targetRevision: {{ .Values.configuration.configurationRevision }}
      ref: values
      {{- end }}
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
  syncPolicy:
    syncOptions:
    - CreateNamespace=false
    automated:
      selfHeal: true
{{ end }}
