{{ include "common.db-secret" . }}
---
{{ include "common.db_setup_sa" . }}
---
{{- if .Values.dbRestore }}
{{ include "common.s3_pg_restore" . }}
{{- else }}
{{ include "common.db_setup_job" . }}
{{- end -}}
{{- if and (.Values.global.externalSecrets.deploy) (.Values.global.externalSecrets.dbCreate) (.Values.postgres.bootstrap) }}
---
{{ include "common.db-push-secret" . }}
---
{{ include "common.secret.db.bootstrap" . }}
{{- end }}