apiVersion: v1
kind: Secret
metadata:
  name: sheepdog-secret
type: Opaque
data:
{{ (.Files.Glob "sheepdog-secret/*").AsSecrets | indent 2 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: sheepdog-creds
type: Opaque
stringData:
  creds.json: |-
    {
      "fence_host": {{ default "fence-postgresql" .Values.secrets.fence.db.host | quote }},
      "fence_username": {{ default "postgres" .Values.secrets.fence.db.username | quote }},
      "fence_password": {{ default .Values.global.postgresql.auth.postgresPassword .Values.secrets.fence.db.password | quote }},
      "fence_database": {{ default .Values.global.postgresql.auth.database .Values.secrets.fence.db.database | quote }},
      "db_host": {{ default "sheepdog-postgresql" .Values.secrets.db.host | quote }},
      "db_username": {{ default "postgres" .Values.secrets.db.username | quote }},
      "db_password": {{ default .Values.global.postgresql.auth.postgresPassword .Values.secrets.db.password | quote }},
      "db_database": {{ default .Values.global.postgresql.auth.database .Values.secrets.db.database | quote }},
      "gdcapi_secret_key": {{ default (randAlphaNum 50) .Values.secrets.gdcapi_secret_key | quote }},
      "hostname": {{ default "ingress.local" .Values.hostname  | quote}}
      "oauth2_client_id": "",
      "oauth2_client_secret": ""
    }