{{ if .Values.global.externalSecrets.deploy }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: funnel-oidc-client
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: {{include "common.SecretStore" .}}
    kind: SecretStore
  target:
    name: funnel-oidc-client
    creationPolicy: Owner
  dataFrom:
  - extract:
      #name of secret in secrets manager
      key: {{ include "funnel-oidc-client" . }}
      conversionStrategy: Default
      decodingStrategy: None
{{- if and .Values.global.externalSecrets.deploy (not .Values.global.externalSecrets.createLocalK8sSecret) }}
{{ include "common.externalSecret.db" . }}
{{- end}}
{{- end }}
