        Postgres: {POSTGRES_CONFIG_PLACEHOLDER: POSTGRES_CONFIG_PLACEHOLDER}
        Plugins:
            Path: plugin-binaries/auth-plugin
            Params:
                OidcClientId: <redacted>




        Postgres:
            Host: abc:5432
            Database: 
            User: 
            Password: 
        Plugins:
