apiVersion: v1
kind: Secret
metadata:
  name: portal-config
data:
{{- range $path, $bytes := .Files.Glob "defaults/*" }}
  {{ ($a := split "/" $path)._1 }}: |
  {{- $bytes | toString | b64enc | nindent 4 }}  
{{- end}}
