apiVersion: v1
kind: Service
metadata:
  name: frontend-framework-service
  labels:
    {{- include "frontend-framework.labels" . | nindent 4 }}
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000 
      name: http
      nodePort: null
    - protocol: TCP 
      port: 443 
      targetPort: 3000 
      name: https
      nodePort: null
  type: ClusterIP
  selector:
    {{- include "frontend-framework.selectorLabels" . | nindent 4 }}
