{{- if and .Values.enabled .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "dataUploadCron.fullname" . }}
  labels:
    {{- include "dataUploadCron.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "dataUploadCron.fullname" . }}
  labels:
    {{- include "dataUploadCron.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "dataUploadCron.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "dataUploadCron.fullname" . }}
{{- end -}}
